import Head from "next/head";
import React from "react";

const About = () => {
	return (
		<div>
			<Head>
				<title>About Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>about</main>
		</div>
	);
};

export default About;
