import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				Lorem ipsum dolor sit amet consectetur
				adipisicing elit. Iure soluta a saepe numquam
				veniam illum illo velit sit, officiis delectus
				fugiat at, mollitia, dolores sapiente officia
				veritatis explicabo deleniti fugit?
			</main>
		</div>
	);
}
