import { Button, Card, Checkbox, Col, Form, Input, Row, Space } from "antd";
import Head from "next/head";
import Image from "next/image";

import Logo from "../public/logo.webp";
import { useRouter } from "next/router";
export default function Login({ setlogin }) {
  const router = useRouter();
  const onFinish = (values) => {
    console.log("Success:", values);
    setlogin(true);
    router.push("/home");
  };

  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };
  const formItemLayout = {
    labelCol: {
      span: 4,
    },
    wrapperCol: {
      span: 14,
    },
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row
        type="flex"
        justify="center"
        align="middle"
        style={{ minHeight: "100vh" }}
      >
        <Col span={10} justify="center" align="middle">
          <Card>
            <Row type="flex" justify="center" align="middle">
              <Image src={Logo} alt="imageLogo" width={100} height={100} />
            </Row>
            <Space
              direction="horizontal"
              style={{
                width: "100%",
                justifyContent: "center",
              }}
            >
              <h3>CYGEN SOLUTION</h3>
            </Space>

            <Form
              {...formItemLayout}
              layout={"vertical"}
              name="basic"
              // labelCol={{
              // 	span: 8,
              // }}
              wrapperCol={{
                span: 20,
              }}
              initialValues={{
                remember: true,
              }}
              onFinish={onFinish}
              onFinishFailed={onFinishFailed}
              autoComplete="off"
              style={{ paddingLeft: "120px" }}
            >
              <Form.Item
                label="Username"
                name="username"
                rules={[
                  {
                    required: true,
                    message: "Please input your username!",
                  },
                ]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Password"
                name="password"
                rules={[
                  {
                    required: true,
                    message: "Please input your password!",
                  },
                ]}
              >
                <Input.Password />
              </Form.Item>

              <Form.Item name="remember" valuePropName="checked">
                <Checkbox>Remember me</Checkbox>
              </Form.Item>

              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  style={{
                    width: "100%",
                  }}
                >
                  Login
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Col>
      </Row>
    </div>
  );
}
